meta_product_name: "Classy"
meta_title: "Classy - Manage class lists effectively"
meta_description: "With Classy, teachers can focus on what matters most. Create your class lists in less time than ever before."
meta_image: "classymeta.png" # should exist in `app/assets/images/`
twitter_account: # required for Twitter Cards
